### ISSUE TITLE
'../../common/mixins.less' wasn't found

### ISSUE THREAD

**Issue by MiniGod** [hugihlynsson/hvad-er-i-bio#2]
Looks like `source/main.less` is `@import`ing files from outside the repo. Could you include them?

```
[00:15:15] Starting 'styles'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: '../../common/mixins.less' wasn't found in file D:\...........\forks\hugihlynsson\hvad-er-i-bio\source\main.less line no. 7
```

[source/main.less:7][less]
```
 6
 7   @import '../../common/mixins.less';
 8   @import '../../common/normalize.less';
 9
```

[less]: https://github.com/hugihlynsson/hvad-er-i-bio/blob/c654caf24fae5ed056683615b42e9e26236c369b/source/main.less#L7

**Comment by hugihlynsson** [comment]
Ooops! Should be fixed in 1efb76ec41:)

**Comment by hugihlynsson** [comment]
@MiniGod Has this been resolved for you?

**Comment by MiniGod** [comment]
Yes! Thank you! :D
