### ISSUE TITLE
Repeating data under the star wars movie

### ISSUE THREAD

**Issue by fannarsh** [hugihlynsson/hvad-er-i-bio#4]
Currently there is something strange happening.
<img width="1280" alt="screen shot 2016-01-10 at 20 06 21" src="https://cloud.githubusercontent.com/assets/58624/12223707/23fa324e-b7d6-11e5-95bb-7e32f93a927d.png">

**Comment by hugihlynsson** [comment]
Wow, this is interesting. Thanks for reporting! When digging into this, it seams as if kvikmyndir.is are returning ridiculous (and potentially straight out wrong) data. I'll contact them and see if they won't fix it!

**Comment by MiniGod** [comment]
I assume this is related. `showplace` with no name:

![image](https://cloud.githubusercontent.com/assets/60520/12430178/1976058e-bee6-11e5-85ee-3e2fc55e42c4.png)

**Comment by hugihlynsson** [comment]
After some investigation, it seems that the data from kvikmyndir.is contained movies that listed a cinema that isn't included in the `theaterList.json`, cinema nr. *15*. When trying to pull a new list, it doesn't seem to be there either. In fact, when looking at what kvikmyndir.is has on their own _bíó_ site, that shows listed in that mysterious cinema are nowhere to be seen. When digging further into the data, it seems that cinema 15 is showing a _lot_ of shows at the same time, leading to my conclusion that it is just gibberish and probably and error. Anyhow, I've fixed this in  ffd643c, which does not allow shows where there are no movies :tada:
