### ISSUE TITLE
Sometimes shows incorrect times for movie theaters

### ISSUE THREAD

**Issue by benediktvaldez** [hugihlynsson/hvad-er-i-bio#5]
Last Saturday I decided to check out a movie, the new Captain America to be precise, and of course I opened one of my favorite websites to pick a movie theater and see available times.

[hvaderibio.is](http://hvaderibio.is) told me that it would be shown at 21:00 in Laugarásbíó, but when I arrive at approx. 20:55 the girl in the booth goes `nope, today it was only shown at 20:00 and at 22:00 – and btw we don't recommend using hvaderibio.is since they often show wrong times` – which made me very sad since I dislike midi.is for browsing available movies on my phone.

Just wanted to let you know @hugihlynsson that there might be a problem somewhere – if I find the time/inspiration to fix it myself I might throw in a PR, but wanted to note this here in case someone else finds it sooner.

**Comment by hugihlynsson** [comment]
Ohh no, that really inconvenient. Reliability is very important part of this service – hence it might turn out as Siri, something that your rarely use. In defence for Hvað er í bíó?, the data is coming incorrectly from kvikmyndir.is. I saw that that they recently opened a new API which might not be as error prone as the one I'm currently using. Anyhow, thanks for the heads-up!

**Comment by hugihlynsson** [comment]
@benediktvaldez I've updated the site with new data from [api.kvikmyndir.is](api.kvikmyndir.is), powered by snaerth/icelandic-movie-api that seems to have more correct data than the previous source. Thanks @snaerth! I've also addressed some bugs and hope the [hvaðeríbíó.is](http://www.hvaderibio.is) experience will be better next time!
