### ISSUE TITLE
Síðan er ekki að sýna neinar myndir.

### ISSUE THREAD

**Issue by AwesomeQuest** [hugihlynsson/hvad-er-i-bio#7]
Síðan sýnir eingar myndir
![image](https://user-images.githubusercontent.com/15609837/69574376-de3e0c80-0fbf-11ea-8de5-2e89b81f3b04.png)
Kanski er API ekki að svara?

kvikmyndir.is er að sýna allt just fine.

**Comment by hugihlynsson** [comment]
Hæ! Það lýtur út fyrir að apinn hafi ekki verið að skila neinum myndum. Hvað er í bíó bakendinn sækir gögn á klukkutíma fresti og það lítur út fyrir að þau hafi dottið inn. Takk fyrir að láta mig vita og vonandi gerist þetta ekki aftur!
